version: '3'
services:
  react:
    container_name: client
    image: maaaaaaaaad/emojmo-client:0.1
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    stdin_open: true
